package promhs;

/**
 *
 * @author AnakAgng Bintang Purnama Dewi_20103019
 */
public class frmSIM extends javax.swing.JFrame {
    frommhs fm;
    frmmtkl mt;
    frmdosn ds;
    /**
     * Creates new form frmSIM
     */
    public frmSIM() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bck = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        Mnfile = new javax.swing.JMenu();
        mnexit = new javax.swing.JMenuItem();
        mhs = new javax.swing.JMenu();
        mat = new javax.swing.JMenu();
        dsn = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout bckLayout = new javax.swing.GroupLayout(bck);
        bck.setLayout(bckLayout);
        bckLayout.setHorizontalGroup(
            bckLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 423, Short.MAX_VALUE)
        );
        bckLayout.setVerticalGroup(
            bckLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 336, Short.MAX_VALUE)
        );

        Mnfile.setText("File");
        Mnfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnfileActionPerformed(evt);
            }
        });

        mnexit.setText("Exit");
        mnexit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnexitActionPerformed(evt);
            }
        });
        Mnfile.add(mnexit);

        jMenuBar1.add(Mnfile);

        mhs.setText("Data Mahasiswa");
        mhs.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mhsMouseClicked(evt);
            }
        });
        mhs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mhsActionPerformed(evt);
            }
        });
        jMenuBar1.add(mhs);

        mat.setText("Data Matakuliah");
        mat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                matMouseClicked(evt);
            }
        });
        jMenuBar1.add(mat);

        dsn.setText("Data Dosen");
        dsn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dsnMouseClicked(evt);
            }
        });
        dsn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dsnActionPerformed(evt);
            }
        });
        jMenuBar1.add(dsn);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bck)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bck, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mhsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mhsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mhsActionPerformed

    private void mhsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mhsMouseClicked
        if(fm == null || fm.isClosed()){
            fm =new frommhs();
            bck.add(fm);
            fm.setLocation(this.getWidth()/2 - fm.getWidth()/2, this.getHeight()/2-fm.getHeight()/2);
            fm.setVisible(true);
        }else{
            fm.setVisible(true);
        }
    }//GEN-LAST:event_mhsMouseClicked

    private void matMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_matMouseClicked
        if(mt == null || mt.isClosed()){
            mt =new frmmtkl();
            bck.add(mt);
            mt.setLocation(this.getWidth()/2 - mt.getWidth()/2, this.getHeight()/2-mt.getHeight()/2);
            mt.setVisible(true);
        }else{
            mt.setVisible(true);
        }
    }//GEN-LAST:event_matMouseClicked

    private void dsnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dsnActionPerformed
      
    }//GEN-LAST:event_dsnActionPerformed

    private void MnfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnfileActionPerformed
        
    }//GEN-LAST:event_MnfileActionPerformed

    private void mnexitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnexitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_mnexitActionPerformed

    private void dsnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dsnMouseClicked
         if(ds == null || ds.isClosed()){
            ds =new frmdosn();
            bck.add(ds);
            ds.setLocation(this.getWidth()/2 - ds.getWidth()/2, this.getHeight()/2-ds.getHeight()/2);
            ds.setVisible(true);
        }else{
            ds.setVisible(true);
        }
    }//GEN-LAST:event_dsnMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmSIM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmSIM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmSIM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmSIM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmSIM().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Mnfile;
    private javax.swing.JDesktopPane bck;
    private javax.swing.JMenu dsn;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu mat;
    private javax.swing.JMenu mhs;
    private javax.swing.JMenuItem mnexit;
    // End of variables declaration//GEN-END:variables
}
